<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TechProfile"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="14.618">
  <properties />
            <testcase name="run_cukes" time="14.618" classname="service_Synchronize_CLICKDB.TechProfile">
                <failure type="cucumber.runtime.CucumberException"
                  message="java.lang.AssertionError: expected [true] but found [false]"
              >
<![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [true] but found [false]
  cucumber.api.testng.TestNGCucumberRunner.runCukes(TestNGCucumberRunner.java:48)
  cucumber.api.testng.AbstractTestNGCucumberTests.run_cukes(AbstractTestNGCucumberTests.java:14)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:497)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:196)
  cucumber.api.testng.AbstractTestNGCucumberTests.run(AbstractTestNGCucumberTests.java:19)
  org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:208)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:635)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:496)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  service_Synchronize_CLICKDB.TechProfile.VerifyingResponse(TechProfile.java:58)
  service_Synchronize_CLICKDB.StepDefinition.Verifying_the_response_for_TechProfile_Creation(StepDefinition.java:35)
  ?.Then Verifying the response for TechProfile Creation(TechProfile.feature:11)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
